apiVersion: v1
kind: Namespace
metadata:
  name: webhook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-sa
  namespace: webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-admin
subjects:
  - kind: ServiceAccount
    name: webhook-sa
    namespace: webhook
roleRef:
  kind: ClusterRole
  name: webhook-admin
  apiGroup: rbac.authorization.k8s.io
---

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: webhook-admin
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - test.kyma-project.io
    resources:
      - testers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - test.kyma-project.io
    resources:
      - testers/status
    verbs:
      - get
      - patch
      - update

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.tester.kyma-project.io
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: webhook-svc
        namespace: webhook
    failurePolicy: Fail
    sideEffects: None
    name: validation.webhook.tester.kyma-project.io
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook.tester.kyma-project.io
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: webhook-svc
        namespace: webhook
    failurePolicy: Fail
    sideEffects: None
    name: webhook.tester.kyma-project.io
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: webhook
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-svc
  namespace: webhook
spec:
  ports:
    - # Define metrics and profiling for them to be accessible within service meshes.
      name: http-metrics
      port: 9090
      targetPort: 9090
    - name: http-profiling
      port: 8008
      targetPort: 8008
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    app: webhook-deployment
    role: webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # Note: the Deployment name must be the same as the Service name specified in
  # config/400-webhook-service.yaml. If you change this name, you must also
  # change the value of WEBHOOK_SERVICE_NAME below.
  name: webhook-deployment
  namespace: webhook
  labels:
    app.kubernetes.io/name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-deployment
      role: webhook
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: webhook-deployment
        role: webhook
    spec:
      serviceAccountName: webhook-sa
      containers:
        - name: webhook
          image: webhook-image:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WEBHOOK_SERVICE_NAME
              value: webhook-svc
            - name: METRICS_DOMAIN
              value: webhook.dev/tester
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: metrics
              containerPort: 9090
            - name: profiling
              containerPort: 8008
            - name: https-webhook
              containerPort: 8443